# Executive URLs
URL_EXECUTIVE_TOKEN = "/executive/entebus/account/token"
URL_EXECUTIVE_OPERATOR_TOKEN = "/executive/company/account/token"
URL_EXECUTIVE_VENDOR_TOKEN = "/executive/business/account/token"
URL_EXECUTIVE_LANDMARK = "/executive/landmark"
URL_EXECUTIVE_BUS_STOP = "/executive/landmark/bus_stop"
URL_EXECUTIVE_ACCOUNT = "/executive/entebus/account"
URL_EXECUTIVE_OPERATOR_ACCOUNT = "/executive/company/account"
URL_EXECUTIVE_VENDOR_ACCOUNT = "/executive/business/account"
URL_EXECUTIVE_COMPANY = "/executive/company"
URL_EXECUTIVE_BUSINESS = "/executive/business"
URL_EXECUTIVE_ROUTE = "/executive/company/route"
URL_EXECUTIVE_LANDMARK_IN_ROUTE = "/executive/company/route/landmark"
URL_EXECUTIVE_BUS = "/executive/company/bus"
URL_EXECUTIVE_SCHEDULE = "/executive/company/schedule"
URL_EXECUTIVE_FARE = "/executive/company/fare"
URL_EXECUTIVE_DUTY = "/executive/company/service/duty"
URL_EXECUTIVE_ROLE = "/executive/role"
URL_EXECUTIVE_ROLE_MAP = "/executive/account/role"
URL_EXECUTIVE_OPERATOR_ROLE = "/executive/company/role"
URL_EXECUTIVE_OPERATOR_ROLE_MAP = "/executive/company/account/role"
URL_EXECUTIVE_VENDOR_ROLE = "/executive/business/role"
URL_EXECUTIVE_VENDOR_ROLE_MAP = "/executive/business/account/role"
URL_EXECUTIVE_PAPER_TICKET = "/executive/company/service/ticket/paper"

# Operator URLs
URL_OPERATOR_TOKEN = "/operator/company/account/token"
URL_OPERATOR_LANDMARK = "/operator/landmark"
URL_OPERATOR_BUS_STOP = "/operator/landmark/"
URL_OPERATOR_ACCOUNT = "/operator/company/account"
URL_OPERATOR_COMPANY = "/operator/company"
URL_OPERATOR_ROUTE = "/operator/company/"
URL_OPERATOR_ROUTE_IN_LANDMARK = "/operator/company/route/landmark"
URL_OPERATOR_BUS = "/operator/company/bus"
URL_OPERATOR_SCHEDULE = "/operator/company/schedule"
URL_OPERATOR_SERVICE = "/operator/company/service"
URL_OPERATOR_FARE = "/operator/company/fare"
URL_OPERATOR_DUTY = "/operator/company/service/duty"
URL_OPERATOR_ROLE = "/operator/company/role"
URL_OPERATOR_ROLE_MAP = "/operator/company/account/role"
URL_OPERATOR_PAPER_TICKET = "/operator/company/service/ticket/paper"

# Vendor URLs
URL_VENDOR_VENDOR_TOKEN = "/vendor/business/account/token"
URL_VENDOR_LANDMARK = "/vendor/landmark"
URL_VENDOR_BUS_STOP = "/vendor/landmark/bus_stop"
URL_VENDOR_ACCOUNT = "	/vendor/business/account"
URL_VENDOR_COMPANY = "	/vendor/company"
URL_VENDOR_BUSINESS = "/vendor/business"
URL_VENDOR_ROUTE = "/vendor/company/route"
URL_VENDOR_ROUTE_IN_LANDMARK = "/vendor/company/route/landmark"
URL_VENDOR_BUS = "	/vendor/company/bus"
URL_VENDOR_SERVICE = "	/vendor/company/service"
URL_VENDOR_FARE = "/vendor/company/fare"
URL_VENDOR_VENDOR_ROLE = "	/vendor/business/role"
URL_VENDOR_VENDOR_ROLE_MAP = "	/vendor/business/account/role"

# Public URLs
URL_PUBLIC_COMPANY = "	/public/company"
URL_PUBLIC_BUSINESS = "/public/business"
