# Executive URLs
EXECUTIVE_TOKEN_URL = "/executive/entebus/account/token"
OPERATOR_TOKEN_URL = "/executive/company/account/token"
VENDOR_TOKEN_URL = "/executive/business/account/token"
LANDMARK_URL = "/executive/landmark"
BUS_STOP_URL = "/executive/landmark/bus_stop"
ACCOUNT_URL = "/executive/entebus/account"
OPERATOR_ACCOUNT_URL = "/executive/company/account"
VENDOR_ACCOUNT_URL = "/executive/business/account"
COMPANY_URL = "/executive/company"
BUSINESS_URL = "/executive/business"
ROUTE_URL = "/executive/company/route"
LANDMARK_IN_ROUTE_URL = "/executive/company/route/landmark"
BUS_URL = "/executive/company/bus"
SCHEDULE_URL = "/executive/company/schedule"
FARE_URL = "/executive/company/fare"
DUTY_URL = "/executive/company/service/duty"
ROLE_URL = "/executive/role"
ROLE_MAP_URL = "/executive/account/role"
OPERATOR_ROLE_URL = "/executive/company/role"
OPERATOR_ROLE_MAP_URL = "/executive/company/account/role"
VENDOR_ROLE_URL = "/executive/business/role"
VENDOR_ROLE_MAP_URL = "/executive/business/account/role"
PAPER_TICKET_URL = "/executive/company/service/ticket/paper"

# Operator URLs
OPERATOR_TOKEN = "/operator/company/account/token"
LANDMARK = "/operator/landmark"
BUS_STOP = "/operator/landmark/"
OPERATOR_ACCOUNT = "/operator/company/account"
COMPANY = "	/operator/company"
ROUTE = "/operator/company/"
ROUTE_IN_LANDMARK = "/operator/company/route/landmark"
BUS = "	/operator/company/bus"
SCHEDULE = "/operator/company/schedule"
SERVICE = "	/operator/company/service"
FARE = "/operator/company/fare"
DUTY = "/operator/company/service/duty"
ROLE = "/operator/company/role"
ROLE_MAP = "/operator/company/account/role"
PAPER_TICKET = "/operator/company/service/ticket/paper"

# Vendor URLs
VENDOR_TOKEN = "/vendor/business/account/token"
LANDMARK = "/vendor/landmark"
BUS_STOP = "/vendor/landmark/bus_stop"
ACCOUNT = "	/vendor/business/account"
COMPANY = "	/vendor/company"
BUSINESS = "/vendor/business"
ROUTE = "/vendor/company/route"
ROUTE_IN_LANDMARK = "/vendor/company/route/landmark"
BUS = "	/vendor/company/bus"
SERVICE = "	/vendor/company/service"
FARE = "/vendor/company/fare"
VENDOR_ROLE = "	/vendor/business/role"
VENDOR_ROLE_MAP = "	/vendor/business/account/role"

# Public URLs
COMPANY = "	/public/company"
BUSINESS = "/public/business"
